allowBuilds:
  vue-demi: true

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - 'vue'
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
