allowBuilds:
  msw: true
  simple-git-hooks: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@playwright/test@1.62.0'
  - '@vue/devtools-core@8.2.0'
  - '@vue/devtools-kit@8.2.0'
  - '@vue/devtools-shared@8.2.0'
  - playwright-core@1.62.0
  - playwright@1.62.0
  - vite-plugin-vue-devtools@8.2.0
  - '@intlify/core-base@11.4.8'
  - '@intlify/devtools-types@11.4.8'
  - '@intlify/message-compiler@11.4.8'
  - '@intlify/shared@11.4.8'
  - '@lucide/vue@1.27.0'
  - vue-i18n@11.4.8
  - eslint-plugin-playwright@2.11.0
  - jsdom@30.0.1
  - vite-plus@0.2.7
  - '@voidzero-dev/vite-plus-core@0.2.7'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.2.7'
  - '@voidzero-dev/vite-plus-darwin-x64@0.2.7'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.7'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.2.7'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.2.7'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.2.7'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.7'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.2.7'
peerDependencyRules:
  allowAny:
    - vue
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
