allowBuilds:
  simple-git-hooks: true
  vue-demi: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.2
  vite-plus: 0.2.2
  vitest: 4.1.9
  '@vitest/coverage-v8': 4.1.9

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - 'vue'
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
